# blocklist
branches:
  except:
  - Developer

# safelist
branches:
  only:
  - master

language: csharp
mono: none
dotnet: 5.0
solution: Mac.Cloudburst.sln

script:
- dotnet restore
- dotnet build
- dotnet test

# blocklist
branches:
except:
- Developer